config/routes.rb
Shirika::Application.routes.draw do
  resources :examples

  resources :resources

  root :to => 'resources#index'

end

app/models/example.rb
class Example
  include Mongoid::Document
end

app/models/resource.rb
class Resource
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :file
  field :link, type: String
  field :title, type: String
  field :created_at, type: DateTime, default: ->{ Time.now }
  field :last_accessed_at, type: DateTime, default: ->{ Time.now }
  field :tags, type: Array
  field :priority, type: Integer, default: 0

  belongs_to :user

  validates :title, presence: true
  validate :resource_presence
  validate :unique_uri

  def resource_presence
    if self.link.blank? && self.file.blank?
      errors.add :base, "You need add a file or a link"
    end
  end

  def uri
    self.file.exists? ? self.file.url : self.link
  end

  def unique_uri
    true
  end
end

app/models/user.rb
class User
	include Mongoid::Document

	field :name, type: String

	has_many :resources

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @examples }
    end
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    @example = Example.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/new
  # GET /examples/new.json
  def new
    @example = Example.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @example }
    end
  end

  # GET /examples/1/edit
  def edit
    @example = Example.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(params[:example])

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render json: @example, status: :created, location: @example }
      else
        format.html { render action: "new" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /examples/1
  # PUT /examples/1.json
  def update
    @example = Example.find(params[:id])

    respond_to do |format|
      if @example.update_attributes(params[:example])
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example = Example.find(params[:id])
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resources }
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
    @resource = Resource.find(params[:id])
    @resource.last_accessed_at = Time.now
    @resource.save    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/new
  # GET /resources/new.json
  def new
    @resource = Resource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource }
    end
  end

  # GET /resources/1/edit
  def edit
    @resource = Resource.find(params[:id])
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(params[:resource])

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render json: @resource, status: :created, location: @resource }
      else
        format.html { render action: "new" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resources/1
  # PUT /resources/1.json
  def update
    @resource = Resource.find(params[:id])

    respond_to do |format|
      if @resource.update_attributes(params[:resource])
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy

    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<h1>Listing examples</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @examples.each do |example| %>
  <tr>
    <td><%= link_to 'Show', example %></td>
    <td><%= link_to 'Edit', edit_example_path(example) %></td>
    <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shirika" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Shirika</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%#= debug flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <%= link_to "Adrian Mejia", "http://adrianmejia.com"%> 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/resources/_form.html.erb
<%= form_for @resource, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <% if @resource.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">x</a>
      <h3><strong><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</strong></h3>
      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :file, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :file, :class => 'text_field' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                resources_path, :class => 'btn' %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resources/index.html.erb
<div id="resources"></div>

app/views/resources/new.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resources/show.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:_type) %>:</strong></dt>
  <dd><%= @resource._type || "-" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:_id) %>:</strong></dt>
  <dd><%= @resource._id  || "-" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= link_to @resource.file.url || "-", @resource.file.url %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= link_to @resource.link || "-", @resource.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @resource.title || "-" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_accessed_at) %>:</strong></dt>
  <dd><%= @resource.last_accessed_at || "-" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @resource.tags || "-" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @resource.user_id || "-" %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              resources_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_resource_path(@resource), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              resource_path(@resource),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<hr>

<div>
  <h4>PDF Viewer</h4>
  <button id="prev" onclick="goPrevious()">&lt;&lt;</button>
  <span id="page_num">Page: 0/0</span>
  <button id="next" onclick="goNext()">&gt;&gt;</button>
  <canvas id="pdf-reader" style="border:1px solid black"></canvas>
</div>

<!-- shows a cool PDF viewer
<hr>
<iframe style="width:100%;height:100%;display:block;" src="/generic/web/viewer.html"></iframe>
 -->